apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mostafaibrahim24/empl-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_API_URL
          value: http://192.168.49.2/api
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
