apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: tcp
    - name: metrics
      port: 9113
      targetPort: 9113
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
      - name: frontend
        image: mostafaibrahim24/empl-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              key: REACT_APP_API_URL
              name: app-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
      
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:1.5.1
        args:
          - "-nginx.scrape-uri=http://localhost:8080/stub_status"
        ports:
          - containerPort: 9113
            name: metrics
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
