apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: frontend 
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
