apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    performance_schema = ON
    performance-schema-consumer-events-statements-current = ON
    performance-schema-consumer-events-statements-history = ON
    performance-schema-consumer-events-statements-history-long = ON
