apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 8080;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri /index.html;
        }

        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
