apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PASSWORD: AgAvSOKiqo97YSio1zeesAytB9s2tJDgAauRNP1a2LOdcyNSiJTvyZj1EhOhclXm/FTL6AXdFYT/OMetvnrS/wcg0jT+rfJGtuecWLJb0zwcGWAWeT+05vMV4mGdPs5lnfk3buhFm1z4blUbbijww71yyqtX8CPxa8d9LVEi2LkSpt6BqcFw/AAsBAO9x2DjueJmBC27q/OlIEw2yrqG2n/+IX8GYTzsCbkSoseXWEARy97Cw2b+aq1XgVtUXOJDIJIq1Q240v6o+HXYdSKFz4jr2Ymxi8ydPtsCeZZeCs8IsZVk9FZ3uTtoQWnEI6X60j7UM2Lml6LaxOTVS4Kd507q+qelmOq2iIgq+Q4NsZr089nX2WLQhgCK/2Iu9Zp8AQ9pUE1tzCNkrdPgqBjdDrWb3CltR48x0yhNMryAUR52A7p+BLVvQ3GEoDbGCwQD67uLJ7xs7r/7yrF0Yuu/Pccf3IDj30fhYLNk7Tr+pbaVSgD7aG6Z9c7vIm6SlCxEC28I9IGTeQj77ZI6FZSwg4QJvrdGeP1aB/xabJX8oCLXsOv19XVAkYMoRJ+rvPFBVgodnjJ6OitJCJiVUAeCf3T9joRaGA0eQxOQZvrHVv0T+GiTHozfC63HFjHDn+PGBYL8Cr2xUhBXuUlpDopOG1JV4JhlnLG6zsgL302AKjE02GOLCoUnZttn+33b90Scpb4YsRq6C9VtHFQ=
    MYSQL_USER: AgBUPzJPjcmBaKq+lZJdnf0ztFQxxe5k4K1P9Ma3IWVta+vvAynRRItSiOdZOslhU/tgdWk1HbSiOYw1qkrWMlkbrJHY+TaXtjWqnbW9Oeyf3sh+tcvy2YOBf7EaJvgWYnk0zXxD2ZqDYhItltqHQ/B9hnMIeJhtpfQE+5z4mqaXivarJfKN5gUWY61I0O3B05nmai5e5tanfemPifRNFuzNVdvsdvMQkEMo6fZt+OrtdHE3D72Y58poq/us6migwja668z4FueFmzQXUyOt2uOTZGItgLjOA0KxaP7qcqIqMBueMq/ov02ME+By+TYdVipzyXqLglHksK/V+Wr8T/2vBCE6HBI0jUfasZWhRe0bOa7CAm7QJ4G4qJGIqDTNC+jJWwbiHR8dIVWIUj1RMLSSvMGE2s39c2b0Na3OIcXRfJd3t0skp2gacljATRQflLkTL838m0ZKHADUm3Y2UOBVqiaiXrFbDV4cpztExR5rRxfoQVwTVgz7iOanisdLFzl6d3LeCLiGyDIzNndaKEHQCGaoMdEIe8xDlxLElaO0k3943ePnkP4LRqvmFRm7Pfmz15OqNi/x1t8Gjjxmju5Nxv+Qzz5+DW3y2yTPLjc7o85ng8fPsB9nZbPlgusoDmyl2/oCkmOMNuAyw2LylW/m/OT6mRPNaXPUTz0OrvVzciGIuLEkY4e7fGMLZQdzRHhC+AfDEdr/4DQ=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque