apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: db-secret
        command:
          - sh
          - -c
          - |
            until mysql -h mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e 'SELECT 1;' >/dev/null 2>&1; do
              echo "Waiting for MySQL..."
              sleep 5
            done
            echo "MySQL is ready!"
      containers:
      - name: backend
        image: mostafaibrahim24/empl-backend:7de8fde
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: db-secret
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "600m"
            memory: "1Gi"
