apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: db-secret
        command:
          - sh
          - -c
          - |
            until mysql -h mysql-0.mysql.default.svc.cluster.local -uroot -e 'SELECT 1;'; do
              echo "Waiting for MySQL..."
              sleep 5
            done
            echo "MySQL is ready!"
      - name: wait-for-mongo
        image: mongo:6.0
        command:
          - sh
          - -c
          - |
            until mongosh --host mongodb-0.mongodb.default.svc.cluster.local --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
              echo "Waiting for MongoDB..."
              sleep 5
            done
            echo "MongoDB is ready!"
      containers:
      - name: backend
        image: mostafaibrahim24/empl-backend:6e80696
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_URL
              name: app-config
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_USERNAME
              name: app-config
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATA_MONGODB_URI
              name: app-config
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          valueFrom:
            configMapKeyRef:
              key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              name: app-config
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "600m"
            memory: "1Gi"
