apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-servicemonitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: mongodb 
  endpoints:
    - port: mongo-exporter
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
