apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mysql 
  endpoints:
    - port: mysql-exporter
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
