apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: mysql-exporter
      protocol: TCP
      port: 9104
      targetPort: 9104
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_DATABASE
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      - name: mysql-exporter
        image: prom/mysqld-exporter
        ports:
          - name: tcp
            protocol: TCP
            containerPort: 9104
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        args:
          - --mysqld.username=root:$MYSQL_ROOT_PASSWORD
          - --mysqld.address=127.0.0.1:3306
          - --collect.global_status
          - --collect.global_variables
          - --collect.info_schema.tables
          - --collect.perf_schema.tablelocks
          - --collect.perf_schema.file_events
          - --collect.perf_schema.eventswaits
          - --collect.perf_schema.indexiowaits
          - --collect.perf_schema.tableiowaits
          - --collect.perf_schema.eventsstatements
          - --collect.perf_schema.eventsstatementssum
        startupProbe:               
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 30
        
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_ROOT_PASSWORD
          - name: DATA_SOURCE_NAME
            value: "root:$(MYSQL_ROOT_PASSWORD)@tcp(127.0.0.1:3306)/"
          # - name: collect.global_status
          #   value: 'true'
          # - name: collect.info_schema.innodb_metrics
          #   value: 'true'
          # - name: collect.auto_increment.columns
          #   value: 'true'
          # - name: collect.info_schema.processlist
          #   value: 'true'
          # - name: collect.binlog_size
          #   value: 'true'
          # - name: collect.info_schema.tablestats
          #   value: 'true'
          # - name: collect.global_variables
          #   value: 'true'
          # - name: collect.info_schema.query_response_time
          #   value: 'true'
          # - name: collect.info_schema.userstats
          #   value: 'true'
          # - name: collect.info_schema.tables
          #   value: 'true'
          # - name: collect.perf_schema.tablelocks
          #   value: 'true'
          # - name: collect.perf_schema.file_events
          #   value: 'true'
          # - name: collect.perf_schema.eventswaits
          #   value: 'true'
          # - name: collect.perf_schema.indexiowaits
          #   value: 'true'
          # - name: collect.perf_schema.tableiowaits
          #   value: 'true'
          # - name: collect.perf_schema.eventsstatements
          #   value: 'true'
          # - name: --collect.perf_schema.eventsstatementssum
          #   value: 'true'
          # - name: --collect.perf_schema.eventsstatementstypes
          #   value: 'true'
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi